[package]
name = "formatable-float"
version = "0.1.0"
authors = ["Andreas Grois <andi@grois.info>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3"
